### Tensor 살펴보기
- Pytorch에서 데이터를 저장하는 자료형
- 모델 입력(input), 출력(output)데이터 형태

1. 모듈 로딩


In [25]:
import torch

Tensor 속성 관련 함수


In [26]:
#매개변수 : 텐서 인스턴스, 텐서 변수명
def printTensor(tensor, name):
    print(f'[Tensor {name}\'s Attribute ]')
    print(f' - tensor.shape : {tensor.shape}')
    print(f' - tensor.ndim : {tensor.ndim}D')
    print(f' - tensor.dtype : {tensor.dtype}')
    print(f' - tensor.device : {tensor.device}')
    print(f' - tensor.requires_grad : {tensor.requires_grad}')
    print(f' - tensor.data \n {tensor.data}')


2. Tensor 생성
- 특정 데이터 타입의 텐서 생성
  - 타입별 텐서 클래스 생성자 활용
  - ex) IntTensor, FloatTensor, BoolTensor()

In [27]:
t1 = torch.IntTensor(10)
t2 = torch.IntTensor([10,20])
t3 = torch.BoolTensor([1,1,0,-1])
t4 = torch.FloatTensor([10, 20])
print(t1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)


In [28]:
print(t2)

tensor([10, 20], dtype=torch.int32)


In [29]:
print(t3)

tensor([ True,  True, False,  True])


In [30]:
print(t4)

tensor([10., 20.])


- tensor 생성 2: 원하는 값으로 텐서 생성 : torch.tensor()

In [31]:
t1 = torch.tensor(10) # scalar, int64
printTensor(t1, 't1')

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.int64
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 10


In [35]:
#dtype 매개변수 : 원하는 데이터타입 지정 가능
t1 = torch.tensor(10.,dtype = torch.bool) # scalar, float32 -> Bool
printTensor(t1,'t1')

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 True


In [36]:
t1 = torch.tensor([[1,2,3]],dtype= torch.int8) #2D data

In [37]:
printTensor(t1,'t1')

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([1, 3])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([[1, 2, 3]], dtype=torch.int8)


- tensor 생성 3:  특정 값으로 채운 tensor = 0, 1 등의 값

In [43]:
#0으로 채우기
t1 = torch.ones((5,5), dtype = torch.int8)

In [44]:
printTensor(t1,'t1')

[Tensor t1's Attribute ]
 - tensor.shape : torch.Size([5, 5])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
 tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int8)


In [46]:
#이미 존재하는 tensor와 동일한 shape로 잡고 값 채우기 : zerosl_like. ones_like

img = torch.tensor([[2,3,4,5,6,7],[2,3,4,5,56,7]])

In [47]:
zero_img = torch.zeros_like(img)
print(img)

tensor([[ 2,  3,  4,  5,  6,  7],
        [ 2,  3,  4,  5, 56,  7]])


In [48]:
one_img = torch.ones_like(img)
print(img)

tensor([[ 2,  3,  4,  5,  6,  7],
        [ 2,  3,  4,  5, 56,  7]])


In [50]:
full_img  = torch.full_like(img, 7)
print(full_img)

tensor([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]])


In [52]:
#대각선 방향으로 1 채우기 : eye()]
t1 = torch.eye(5)
print(t1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [54]:
#대각선 방향으로 1 채우기 : eye()]
t1 = torch.eye(3)
print(t1),

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


(None,)

In [55]:
#ramdom
torch.manual_seed(12)
t5 = torch.rand(2,3)
t6 = torch.randn(2,3)
t7 = torch.randint(low = 1, high = 10, size=(2,3))

- NDarray 객체 활용 -> Numpy 객체로 값을 채운 tensor : torch.from_numpy(), torch.as_tensor(), tensor()

In [56]:
import numpy as np

arr = np.array([11,22,33])
t1 = torch.from_numpy(arr)

In [57]:
print(t1)

tensor([11, 22, 33], dtype=torch.int32)


In [58]:
t2 = torch.as_tensor(arr)
print(t2)

tensor([11, 22, 33], dtype=torch.int32)


In [60]:
t3 =torch. tensor(arr)
print(t3)

tensor([11, 22, 33], dtype=torch.int32)


In [62]:
#ndarray 원소 변경
arr[0]=100

#from_numpy(), as_tensor() => 데이터 공유
#tensor() => 복사본 생성
print(arr, t1, t2, t3, sep='\n')

[100  22  33]
tensor([100,  22,  33], dtype=torch.int32)
tensor([100,  22,  33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)
