### Tensor 원소 / 요소 접근
- 인덱싱 / 슬라이싱

In [1]:
# 모듈 로딩
import torch

In [2]:
# 텐서 생성
points = torch.tensor([[4.,2.], [5., 3.],[6.,4]], dtype= torch.int16)
points

C:\Users\kdp\AppData\Local\Temp\ipykernel_1452\1856089716.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  points = torch.tensor([[4.,2.], [5., 3.],[6.,4]], dtype= torch.int16)


tensor([[4, 2],
        [5, 3],
        [6, 4]], dtype=torch.int16)

In [7]:
# 텐서 원소 1개 접근
# data [3] extract
# 마지막 [4] extract
print(points[1,1])

print(points[-1, -1])

tensor(3, dtype=torch.int16)
tensor(4, dtype=torch.int16)


In [4]:
#1번 행부터 나머지 모든 행 추출하기
print(points[1:])

tensor([[5, 3],
        [6, 4]], dtype=torch.int16)


-BROADCASTING

In [17]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3,4]])
print(f'm1.shape = {m1.shape}, m2.shape = {m2.shape}')
m3 = m1 + m2
m3

m1.shape = torch.Size([1, 2]), m2.shape = torch.Size([1, 2])


tensor([[4., 6.]])

In [18]:
print(f'm3.shape=>{m3.shape}\nm3=>\n{m3}')

m3.shape=>torch.Size([1, 2])
m3=>
tensor([[4., 6.]])


In [12]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])

print(f'm1.shape = {m1.shape}, m2.shape = {m2.shape}')

m1.shape = torch.Size([1, 2]), m2.shape = torch.Size([2, 1])


In [13]:
# 곱셈
m3 = m1 * m2
print(f'm3.shape=>{m3.shape}\nm3=>{m3}')

m3.shape=>torch.Size([2, 2])
m3=>tensor([[3., 6.],
        [4., 8.]])


In [14]:
m4 = m1.mul(m2)
print(f'm4.shape=>{m4.shape}\nm4=>{m4}')

m4.shape=>torch.Size([2, 2])
m4=>tensor([[3., 6.],
        [4., 8.]])


In [15]:
# 원소 단위 연산 수행 메서드
m1.add(m2), m1.sub(m2), m1.mul(m2), m1.div(m2)

(tensor([[4., 5.],
         [5., 6.]]),
 tensor([[-2., -1.],
         [-3., -2.]]),
 tensor([[3., 6.],
         [4., 8.]]),
 tensor([[0.3333, 0.6667],
         [0.2500, 0.5000]]))

In [19]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
m3 = m1+m2

print(m3,m3.shape)

tensor([[4., 5.]]) torch.Size([1, 2])


In [20]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
m3 = m1+m2

print(m3,m3.shape)

tensor([[4., 5.],
        [5., 6.]]) torch.Size([2, 2])


In [21]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])

print(f'shape of Matrix 1: {m1.shape}')
print(f'shape of Matrix 2: {m2.shape}')

print(m1 * m2)
print(m1.mul(m2))

shape of Matrix 1: torch.Size([2, 2])
shape of Matrix 2: torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])
