### Tensor Shape 변경

- reshape(), view() : 원소 개수 유지됨, 기존 텐서 공유


In [1]:
#모듈 로딩
import torch

In [2]:
# 텐서 데이터 생성
t1 = torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape,t1.ndim)

torch.Size([2, 3]) 2


In [3]:
#[2,3]==>[3,2] 형 변경 : 원소 개수 동일(6)

t1.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [7]:
# [2 * 3] ==> [6 * 1]
# -1 : 원소 수를 알아서 할당
t1.view(6,1)
t1.view(-1,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [8]:
# tensor.reshape()

t1.reshape(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [9]:
# 원소 수 유지되어야 함
#t1.reshape(-1,7)
#runtimeError

- 전치 : 열 <-> 행 변경

In [17]:
print(t1.shape)
t2 = t1.T
print(t2.shape, t2.is_contiguous())

torch.Size([2, 3])
torch.Size([3, 2]) False


In [18]:
#RuntimeError: view size is not compatible with input tensor's size and stride
#t2.view(-1,6)

t3 = t2.reshape(-1,6)
print(t3,t3.is_contiguous())

tensor([[1, 4, 2, 5, 3, 6]]) True


### 텐서 데이터의 메모리 저장 정보 : 메타데이터
- 현재 저장형태, 검색 방향 정보, 시작 정보

In [21]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape,t1.ndim)
print('t1.storage(): ' ,t1.storage())
print('t1. storage_offset(): ',t1.storage_offset())
print('t1. stride(): ',t1.stride())
print('t1. is_contiguous(): ',t1.is_contiguous())

torch.Size([2, 3]) 2
t1.storage():   1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t1. storage_offset():  0
t1. stride():  (3, 1)
t1. is_contiguous():  True


In [22]:
t2 = t1.view(-1,2)

In [23]:
print(t2.shape,t2.ndim)
print('t2.storage(): ' ,t2.storage())
print('t2. storage_offset(): ',t2.storage_offset())
print('t2. stride(): ',t2.stride())
print('t2. is_contiguous(): ',t2.is_contiguous())

torch.Size([3, 2]) 2
t2.storage():   1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t2. storage_offset():  0
t2. stride():  (2, 1)
t2. is_contiguous():  True


### 차원 제거 / 추가
- tensor.squeeze() : 텐서에서 차원이 1인 것 제거
- tensor.unsqueeze(dim): 텐서에서 차원이 1인 것 추가

In [30]:
t1 = torch.tensor([[1,2],[3,4]])
t2 = torch.tensor([[1,2,3,4]])
t3 = torch.tensor([[[1,2,3,4]]])


In [31]:
print(f't1 = {t1.shape},{t1.ndim}D')
print(f't2 = {t2.shape},{t2.ndim}D')
print(f't3 = {t3.shape},{t3.ndim}D')

t1 = torch.Size([2, 2]),2D
t2 = torch.Size([1, 4]),2D
t3 = torch.Size([1, 1, 4]),3D


In [32]:
t11 = t1.squeeze()
t22 = t2.squeeze()
t33 = t3.squeeze()
print(f't1 차원 축소 = {t11.shape},{t11.ndim}D')
print(f't2 차원 축소= {t22.shape},{t22.ndim}D')
print(f't3 차원 축소= {t33.shape},{t33.ndim}D')

t1 차원 축소 = torch.Size([2, 2]),2D
t2 차원 축소= torch.Size([4]),1D
t3 차원 축소= torch.Size([4]),1D


## 원소 / 요소 수 변경 없이 1차원 증가 시키기 : unsqueeze(dim)

In [34]:
print('t1정보', t1.shape,t1.ndim,'D',t1.data_ptr())

t1정보 torch.Size([2, 2]) 2 D 3219270992256


In [38]:
t11 = t1.unsqueeze(dim=0)
t22 = t1.unsqueeze(dim=-1)

print(f't1 차원추가 : {t11.shape}, {t11.ndim}D, {t11.data_ptr()}, {t11.stride()}')
print(f't1 차원추가 : {t22.shape}, {t22.ndim}D, {t22.data_ptr()}, {t22.stride()}')

t1 차원추가 : torch.Size([1, 2, 2]), 3D, 3219270992256, (4, 2, 1)
t1 차원추가 : torch.Size([2, 2, 1]), 3D, 3219270992256, (2, 1, 1)
