###  텐서 연결 / 결합

In [1]:
#모듈 로딩
import torch

In [24]:
#텐서 데이터 생성
torch.manual_seed(12)

#임의의 0.<= ~ <1. 실수
x = torch.rand(2, 10)

#임의의 정수 low<= ~ <high
y = torch.randint(0, 2,(10,))
y2 = torch.randint(0, 2,(2,10))


In [25]:
print(f'x = {x.shape},{x.ndim}D')
print(f'y2 = {y2.shape},{y2.ndim}D')


x = torch.Size([2, 10]),2D
y2 = torch.Size([2, 10]),2D


In [26]:
# tensor 연결 : cat([tensor 1, tensor2, ...])
#torch.cat([x, y], dim=1)
#RuntimeError: Tensors must have same number of dimensions: got 2 and 1

In [27]:
xy1 = torch.cat([x,y2], dim = 1)

In [28]:
print(f'x,y1=> {xy1.shape},{xy1.ndim}D')

x,y1=> torch.Size([2, 20]),2D


In [30]:
xy1.max(dim = 1)

torch.return_types.max(
values=tensor([1., 1.]),
indices=tensor([10, 12]))

In [33]:
# 행단위로 최대값 및 최대값의 인덱스
max_value = xy1.max(dim=1)[0]
max_index = xy1.max(dim=1)[1]

max_value, max_index

(tensor([1., 1.]), tensor([10, 12]))

In [35]:
# 열 단위로 최대값 및 최대값의 인덳
max_value = xy1.max(dim=0)[0]
max_index = xy1.max(dim = 0)[1]

max_value, max_index


(tensor([0.4657, 0.6948, 0.5830, 0.6318, 0.5559, 0.1272, 0.9790, 0.8443, 0.7312,
         0.7224, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000]),
 tensor([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]))

In [38]:
import pandas as pd
data = pd.DataFrame({'A':[10,11],'B':[20,22],'C':[30,33]})

data.max(), data.max(axis = 1)

(A    11
 B    22
 C    33
 dtype: int64,
 0    30
 1    33
 dtype: int64)

###Tensor 차원 . 형태 변경

In [39]:
t1 = torch.tensor([[[1,2,3],[11,22,33]]])

print(t1.shape, t1.ndim)

torch.Size([1, 2, 3]) 3


In [40]:
#2개의 차원을 변경하는 메서드
t11= t1.transpose(0,2)
print(f't11 = {t11.shape},{t11.ndim}D')

t11 = torch.Size([3, 2, 1]),3D


In [42]:
#모든 차원을 변경하는 메서드

t22 = t1.permute(1,2,0)
print(f't22 = {t22.shape},{t22.ndim}D')

t22 = torch.Size([2, 3, 1]),3D


In [43]:
print(f'{t1.data_ptr()},{t22.data_ptr()},{t11.data_ptr()}')

2970893158528,2970893158528,2970893158528


In [44]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [45]:
torch.eye(1,3)

tensor([[1., 0., 0.]])