### softmax(), sigmoid() <hr>

- sigmoid() : y = wx+b 결과를 한 개만 전달 => 반환 : 0.0 ~ 1.0 사이의 값으로 변환  -> 이진분류
- softmax() : y = wx+b 결과를 여러 개 전달 => 반환 : 여러 개의 결과값의 합이 1.0이 되도로 변환 -> 다중분류

In [1]:
# 모듈 로딩
import torch                       # pytorch 기본 모듈, 텐서 / 기본 함수들
import torch.nn.functional as F    # pytorch 인공신경망 관련 함수들

In [2]:
# 임의 데이터 생성
data1 = torch.tensor([1,2,1,1,2])
data1.shape

torch.Size([5])

In [3]:
F.sigmoid(data1)

tensor([0.7311, 0.8808, 0.7311, 0.7311, 0.8808])

In [4]:
input= torch.randn(2,3)
input

tensor([[ 1.0987,  0.7799, -0.7224],
        [ 0.5399, -0.8084, -0.7417]])

In [7]:
output= F.softmax(input)
output.sum(dim=1)

C:\Users\kdp\AppData\Local\Temp\ipykernel_17644\3373759269.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output= F.softmax(input)


tensor([1., 1.])

In [8]:
output.max(dim=1)

torch.return_types.max(
values=tensor([0.5294, 0.6505]),
indices=tensor([0, 0]))