## 

In [31]:
import torch
import torch.nn as nn
from torchinfo import summary

class Net(nn.Module):
    def __init__(self):  #모델 구성 요소 생성 & 구조 설정
        super(Net, self).__init__()
        
        self.fc1 = nn.Linear(8,4)
        self.fc2 = nn.Linear(4,2)
        self.fc3 = nn.Linear(2,1)
        
    def forward(self,x):  #순방향 학습 진행 함수
        return self.fc3(self.fc2(self.fc1(x)))

In [32]:
#모델 인스턴스 생성

model = Net()

model  # 구조 확인

summary(model) #모델 구조를 깔쌈하게 정리해서 보여준다! dropout 연산 안 함. ->파라미터 없음.
'''
w + b
8 + 1
8 + 1
8 + 1
8 + 1
===> total 36

4 + 1
4 + 1
===> total 10

2 + 1
===> total 3
'''

Layer (type:depth-idx)                   Param #
Net                                      --
├─Linear: 1-1                            36
├─Linear: 1-2                            10
├─Linear: 1-3                            3
Total params: 49
Trainable params: 49
Non-trainable params: 0

In [19]:
#모델 인스턴스의 속성 확인
#모델의 특정 층 추출
model.fc1

model.fc1.weight, model.fc1.bias

(Parameter containing:
 tensor([[ 0.5148,  0.5801, -0.4365,  0.3305,  0.2385, -0.5381, -0.3244, -0.0313],
         [-0.4270, -0.0837, -0.1724,  0.0401, -0.5460, -0.4777, -0.6960,  0.1932],
         [-0.3869,  0.0344, -0.4710, -0.4765,  0.4335, -0.4611, -0.2751,  0.1702],
         [-0.4462,  0.5620, -0.4057, -0.3965,  0.2878, -0.1948,  0.2762, -0.1972]],
        requires_grad=True),
 Parameter containing:
 tensor([0.1533, 0.0528, 0.2027, 0.2806], requires_grad=True))

In [20]:
model.parameters()  #iterater = 반복 객체 => 반복문

<generator object Module.parameters at 0x0000026E7DF46900>

In [21]:
for param in model.parameters(): # 파라미터 값
    print(param, end='\n\n')

Parameter containing:
tensor([[ 0.5148,  0.5801, -0.4365,  0.3305,  0.2385, -0.5381, -0.3244, -0.0313],
        [-0.4270, -0.0837, -0.1724,  0.0401, -0.5460, -0.4777, -0.6960,  0.1932],
        [-0.3869,  0.0344, -0.4710, -0.4765,  0.4335, -0.4611, -0.2751,  0.1702],
        [-0.4462,  0.5620, -0.4057, -0.3965,  0.2878, -0.1948,  0.2762, -0.1972]],
       requires_grad=True)

Parameter containing:
tensor([0.1533, 0.0528, 0.2027, 0.2806], requires_grad=True)

Parameter containing:
tensor([[ 0.3289,  0.2279,  0.3618, -0.4762],
        [ 0.4467, -0.2533, -0.2975, -0.2321]], requires_grad=True)

Parameter containing:
tensor([0.0329, 0.1276], requires_grad=True)

Parameter containing:
tensor([[-0.4725,  0.0181]], requires_grad=True)

Parameter containing:
tensor([0.0014], requires_grad=True)


In [22]:
#모델의 각 층별 W, b 텐서 정보 확인

for param in model.named_parameters():  #이름 + 파라미터 값
    print(param, end='\n\n')

('fc1.weight', Parameter containing:
tensor([[ 0.5148,  0.5801, -0.4365,  0.3305,  0.2385, -0.5381, -0.3244, -0.0313],
        [-0.4270, -0.0837, -0.1724,  0.0401, -0.5460, -0.4777, -0.6960,  0.1932],
        [-0.3869,  0.0344, -0.4710, -0.4765,  0.4335, -0.4611, -0.2751,  0.1702],
        [-0.4462,  0.5620, -0.4057, -0.3965,  0.2878, -0.1948,  0.2762, -0.1972]],
       requires_grad=True))

('fc1.bias', Parameter containing:
tensor([0.1533, 0.0528, 0.2027, 0.2806], requires_grad=True))

('fc2.weight', Parameter containing:
tensor([[ 0.3289,  0.2279,  0.3618, -0.4762],
        [ 0.4467, -0.2533, -0.2975, -0.2321]], requires_grad=True))

('fc2.bias', Parameter containing:
tensor([0.0329, 0.1276], requires_grad=True))

('fc3.weight', Parameter containing:
tensor([[-0.4725,  0.0181]], requires_grad=True))

('fc3.bias', Parameter containing:
tensor([0.0014], requires_grad=True))


# Layer의 가중치 설정하기

In [28]:
#모델 구성의 모든 Layer 가져오기"

for child in model.children():
    print(child, end='\n\n')
    
for child in model.named_children():
    print(child, end='\n\n')

Linear(in_features=8, out_features=4, bias=True)

Linear(in_features=4, out_features=2, bias=True)

Linear(in_features=2, out_features=1, bias=True)

('fc1', Linear(in_features=8, out_features=4, bias=True))

('fc2', Linear(in_features=4, out_features=2, bias=True))

('fc3', Linear(in_features=2, out_features=1, bias=True))


In [24]:
#xavier 알고리즘 가중치 초기화

nn.init.xavier_uniform_(model.fc1.weight)

Parameter containing:
tensor([[-0.3755,  0.2058,  0.2879,  0.5911,  0.2068,  0.2280,  0.6007, -0.4375],
        [-0.2706, -0.2101,  0.2220,  0.1961, -0.4297,  0.4360,  0.0599, -0.5759],
        [-0.3695,  0.2915, -0.6399,  0.7000,  0.0171, -0.2625, -0.4036,  0.1172],
        [ 0.0791, -0.1382,  0.5802, -0.6101,  0.7069, -0.5976,  0.5523, -0.3192]],
       requires_grad=True)

In [26]:
#he(=kaiming) 알고리즘 가중치 초기화

nn.init.kaiming_uniform_(model.fc1.weight)

Parameter containing:
tensor([[ 0.3215, -0.5955, -0.1809,  0.6513,  0.7802, -0.1798,  0.7231, -0.4332],
        [ 0.5107,  0.1271,  0.5626, -0.3812, -0.2380, -0.1535, -0.0785, -0.3702],
        [ 0.1901,  0.6924, -0.6653, -0.6781,  0.4008, -0.5854, -0.5889, -0.6057],
        [-0.6023, -0.2513, -0.1052,  0.5360, -0.1561,  0.3036,  0.1397,  0.1600]],
       requires_grad=True)

In [30]:
import torchviz
import torchinfo

In [33]:
torch.save(model,'../datas/model/mymd.pt')
